# Generated by Django 3.1.2 on 2021-01-02 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiniela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=9, verbose_name='Temporada')),
                ('jornada', models.CharField(max_length=2, verbose_name='Jornada')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=30, verbose_name='Local')),
                ('visitante', models.CharField(max_length=30, verbose_name='Visitante')),
                ('uno', models.IntegerField(blank=True, null=True, verbose_name='Uno')),
                ('x', models.IntegerField(blank=True, null=True, verbose_name='X')),
                ('dos', models.IntegerField(blank=True, null=True, verbose_name='Dos')),
                ('quiniela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.quiniela')),
                ('votantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pleno',
            fields=[
                ('local', models.CharField(max_length=30, verbose_name='Local')),
                ('visitante', models.CharField(max_length=30, verbose_name='Visitante')),
                ('ceroL', models.IntegerField(blank=True, null=True, verbose_name='CeroV')),
                ('unoL', models.IntegerField(blank=True, null=True, verbose_name='UnoV')),
                ('dosL', models.IntegerField(blank=True, null=True, verbose_name='DosV')),
                ('quiniela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.quiniela')),
                ('votantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
