# Generated by Django 3.1.2 on 2021-01-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pleno',
            name='ceroV',
            field=models.IntegerField(blank=True, null=True, verbose_name='CeroV'),
        ),
        migrations.AddField(
            model_name='pleno',
            name='dosV',
            field=models.IntegerField(blank=True, null=True, verbose_name='DosV'),
        ),
        migrations.AddField(
            model_name='pleno',
            name='masL',
            field=models.IntegerField(blank=True, null=True, verbose_name='masL'),
        ),
        migrations.AddField(
            model_name='pleno',
            name='masV',
            field=models.IntegerField(blank=True, null=True, verbose_name='masV'),
        ),
        migrations.AddField(
            model_name='pleno',
            name='unoV',
            field=models.IntegerField(blank=True, null=True, verbose_name='UnoV'),
        ),
        migrations.AlterField(
            model_name='pleno',
            name='ceroL',
            field=models.IntegerField(blank=True, null=True, verbose_name='CeroL'),
        ),
        migrations.AlterField(
            model_name='pleno',
            name='dosL',
            field=models.IntegerField(blank=True, null=True, verbose_name='DosL'),
        ),
        migrations.AlterField(
            model_name='pleno',
            name='unoL',
            field=models.IntegerField(blank=True, null=True, verbose_name='UnoL'),
        ),
    ]
