# Generated by Django 3.1.2 on 2021-01-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210103_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleno',
            name='masL',
            field=models.IntegerField(blank=True, null=True, verbose_name='MasL'),
        ),
        migrations.AlterField(
            model_name='pleno',
            name='masV',
            field=models.IntegerField(blank=True, null=True, verbose_name='MasV'),
        ),
    ]
