# Generated by Django 3.1.2 on 2021-01-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210103_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='noticiaPrimera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.TextField(verbose_name='Titular')),
                ('resumen', models.TextField(verbose_name='Resumen')),
                ('link', models.TextField(verbose_name='Link')),
            ],
        ),
    ]
