# Generated by Django 3.1.2 on 2021-01-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_noticiaprimera_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaprimera',
            name='division',
            field=models.IntegerField(verbose_name='Division'),
        ),
    ]
