# Generated by Django 3.1.2 on 2021-01-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210111_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaprimera',
            name='division',
            field=models.CharField(max_length=30, verbose_name='Division'),
        ),
    ]
